// This file is auto-generated by comparison.sh
export const tools = [
  "kohomology",
  "sage"
] as const
export type Tool = (typeof tools)[number]

export const targets = [
  "FreeLoopSpaceOf2Sphere",
  "FreeLoopSpaceOf2SphereWithMultiGrading"
] as const
export type Target = (typeof targets)[number]
