package com.github.shwaka.kohomology.field

import com.github.shwaka.kococo.debugOnly
import kotlin.Exception
import kotlin.math.absoluteValue
import kotlin.math.sign

private fun gcd(a: Long, b: Long): Long {
    if (a == 0L || b == 0L) {
        throw Exception("gcd not defined for 0")
    }
    val aAbs = a.absoluteValue
    val bAbs = b.absoluteValue
    return if (aAbs >= bAbs) {
        gcdInternal(aAbs, bAbs)
    } else {
        gcdInternal(bAbs, aAbs)
    }
}

private fun gcdInternal(a: Long, b: Long): Long {
    // arguments should satisfy a >= b >= 0
    if (b == 0L) return a
    return gcdInternal(b, a % b)
}

private fun reduce(numerator: Long, denominator: Long): Pair<Long, Long> {
    if (numerator == 0L) return Pair(0, 1)
    val g = gcd(numerator, denominator)
    val num = numerator * denominator.sign / g
    val den = denominator.absoluteValue / g
    return Pair(num, den)
}

class LongRational(numerator: Long, denominator: Long) : RationalScalar<LongRational> {
    private val numerator: Long
    private val denominator: Long
    init {
        // 約分 と denominator > 0
        // 生成時に毎回やるのは無駄な気もする
        val red = reduce(numerator, denominator)
        this.numerator = red.first
        this.denominator = red.second
    }
    override val field = LongRationalField
    override operator fun plus(other: LongRational): LongRational {
        debugOnly {
            val num1 = this.numerator
            val den1 = this.denominator
            val num2 = other.numerator
            val den2 = other.denominator
            OverflowDetector.assertNoOverflow(num1, den1, num2, den2) { n1, d1, n2, d2 ->
                n1 * d2 + n2 * d1
            }
            OverflowDetector.assertNoOverflow(num1, den1, num2, den2) { _, d1, _, d2 ->
                d1 * d2
            }
        }
        val numerator = this.numerator * other.denominator + other.numerator * this.denominator
        val denominator = this.denominator * other.denominator
        return LongRational(numerator, denominator)
    }
    override operator fun times(other: LongRational): LongRational {
        debugOnly {
            OverflowDetector.assertNoOverflow(this.numerator, other.numerator) { a, b -> a * b }
            OverflowDetector.assertNoOverflow(this.denominator, other.denominator) { a, b -> a * b }
        }
        return LongRational(this.numerator * other.numerator, this.denominator * other.denominator)
    }
    override operator fun div(other: LongRational): LongRational {
        debugOnly {
            OverflowDetector.assertNoOverflow(this.numerator, other.denominator) { a, b -> a * b }
            OverflowDetector.assertNoOverflow(this.denominator, other.numerator) { a, b -> a * b }
        }
        if (other == LongRational(0, 1)) {
            throw ArithmeticException("division by zero (Rational(0, 1))")
        }
        return LongRational(this.numerator * other.denominator, this.denominator * other.numerator)
    }

    override fun toString(): String {
        return when {
            this.numerator == 0L -> {
                "0"
            }
            this.denominator == 1L -> {
                this.numerator.toString()
            }
            else -> {
                "${this.numerator}/${this.denominator}"
            }
        }
    }

    override fun unwrap(): LongRational {
        return this
    }

    override fun equals(other: Any?): Boolean {
        // generated by Intellij Idea
        if (this === other) return true
        if (other == null) return false
        if (this::class != other::class) return false

        other as LongRational

        if (numerator != other.numerator) return false
        if (denominator != other.denominator) return false

        return true
    }

    override fun hashCode(): Int {
        // generated by Intellij Idea
        var result = numerator
        result = 31 * result + denominator
        return result.toInt()
    }
}

object LongRationalField : RationalField<LongRational> {
    override fun fromInt(n: Int): LongRational {
        return LongRational(n.toLong(), 1)
    }

    override fun fromIntPair(numerator: Int, denominator: Int): LongRational {
        return LongRational(numerator.toLong(), denominator.toLong())
    }

    override fun toString(): String {
        return "LongRationalField"
    }

    override val zero = LongRational(0, 1)
    override val one = LongRational(1, 1)
}
