#! /bin/bash

# directories="kohomology kohomology-js"
directories="kohomology"
for d in $directories; do
    (
        cd $d
        ./gradlew kc # This will run ktlintCheck for ALL projects (see kohomology/build.gradle.kts)
    )
done
