/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.shwaka.kohomology

import com.github.shwaka.kohomology.field.BigRationalField
import com.github.shwaka.kohomology.field.Field
import com.github.shwaka.kohomology.field.Fp
import com.github.shwaka.kohomology.field.IntRationalField
import com.github.shwaka.kohomology.field.RationalField
import io.kotest.core.spec.style.StringSpec
import io.kotest.core.spec.style.stringSpec
import io.kotest.matchers.compilation.shouldCompile
import io.kotest.matchers.compilation.shouldNotCompile
import io.kotest.matchers.shouldBe

fun <S> fieldTest(field: Field<S>) = stringSpec {
    "1 + 2 should be 3" {
        (field.fromInt(1) + field.fromInt(2)) shouldBe field.fromInt(3)
    }
    "1 - 1 should be 0" {
        (field.fromInt(1) - field.fromInt(1)) shouldBe field.fromInt(0)
    }
}

fun <S> rationalTest(field: RationalField<S>) = stringSpec {
    "1/2 + 1/3 should be 5/6" {
        val a = field.fromIntPair(1, 2)
        val b = field.fromIntPair(1, 3)
        (a + b) shouldBe field.fromIntPair(5, 6)
    }
    "2/6 should be 1/3" {
        field.fromIntPair(2, 6) shouldBe field.fromIntPair(1, 3)
    }
    "1/(-2) should be (-1)/2" {
        field.fromIntPair(1, -2) shouldBe field.fromIntPair(-1, 2)
    }
    "0/2 should be 0/1" {
        field.fromIntPair(0, 2) shouldBe field.fromIntPair(0, 1)
    }
    "5/6 * 2/3 should be 5/9" {
        (field.fromIntPair(5, 6) * field.fromIntPair(2, 3)) shouldBe field.fromIntPair(5, 9)
    }
}

class IntRationalTest : StringSpec({
    include(fieldTest(IntRationalField))
    include(rationalTest(IntRationalField))
})

class BigRationalTest : StringSpec({
    include(fieldTest(BigRationalField))
    include(rationalTest(BigRationalField))
})

class IntModpTest : StringSpec({
    val fp = Fp(5)
    include(fieldTest(fp))
})

class CompileTest : StringSpec({
    "IntRational + IntRational should compile" {
        val codeSnippet =
            """
            import com.github.shwaka.kohomology.field.IntRational
            val foo = IntRational(0, 1) + IntRational(1, 0)
            """ // compiles, but runtime error
        codeSnippet.shouldCompile()
    }
    "Rational + IntModp should not compile" {
        val codeSnippet =
            """
            import com.github.shwaka.kohomology.field.Rational
            import com.github.shwaka.kohomology.field.IntModp
            val foo = IntRational(0, 1) + IntModp(0, 7)
            """
        codeSnippet.shouldNotCompile()
    }
})
