package com.github.shwaka.kohomology.free.monoid

import com.github.shwaka.kohomology.dg.Boundedness
import io.kotest.assertions.throwables.shouldNotThrowAny
import io.kotest.core.spec.style.FreeSpec
import io.kotest.matchers.shouldBe

class NCFreeGMonoidTest : FreeSpec({
    tags(gMonoidTag)

    "empty indeterminate list should be allowed" {
        shouldNotThrowAny {
            NCFreeGMonoid<StringIndeterminateName>(emptyList())
        }
    }

    "should be bounded below and above by 0 if indeterminate list is empty" {
        val monoid = NCFreeGMonoid<StringIndeterminateName>(emptyList())
        monoid.boundedness shouldBe Boundedness(upperBound = 0, lowerBound = 0)
    }

    "should be bounded below if generated by positive degrees" {
        val indeterminateList = listOf(
            Indeterminate("x", 2),
            Indeterminate("y", 3),
        )
        val monoid = NCFreeGMonoid(indeterminateList)
        monoid.boundedness shouldBe Boundedness(upperBound = null, lowerBound = 0)
    }

    "should be bounded above if generated by negative degrees" {
        val indeterminateList = listOf(
            Indeterminate("x", -2),
            Indeterminate("y", -3),
        )
        val monoid = NCFreeGMonoid(indeterminateList)
        monoid.boundedness shouldBe Boundedness(upperBound = 0, lowerBound = null)
    }
})
