package com.github.shwaka.kohomology.util.list

// for n in $(seq 6 30); do echo "public operator fun <T> List<T>.component$n(): T = this[$(expr $n - 1)]"; done
// for n in $(seq 6 30); do echo "import com.github.shwaka.kohomology.util.list.component$n"; done

public operator fun <T> List<T>.component6(): T = this[5]
public operator fun <T> List<T>.component7(): T = this[6]
public operator fun <T> List<T>.component8(): T = this[7]
public operator fun <T> List<T>.component9(): T = this[8]
public operator fun <T> List<T>.component10(): T = this[9]
public operator fun <T> List<T>.component11(): T = this[10]
public operator fun <T> List<T>.component12(): T = this[11]
public operator fun <T> List<T>.component13(): T = this[12]
public operator fun <T> List<T>.component14(): T = this[13]
public operator fun <T> List<T>.component15(): T = this[14]
public operator fun <T> List<T>.component16(): T = this[15]
public operator fun <T> List<T>.component17(): T = this[16]
public operator fun <T> List<T>.component18(): T = this[17]
public operator fun <T> List<T>.component19(): T = this[18]
public operator fun <T> List<T>.component20(): T = this[19]
public operator fun <T> List<T>.component21(): T = this[20]
public operator fun <T> List<T>.component22(): T = this[21]
public operator fun <T> List<T>.component23(): T = this[22]
public operator fun <T> List<T>.component24(): T = this[23]
public operator fun <T> List<T>.component25(): T = this[24]
public operator fun <T> List<T>.component26(): T = this[25]
public operator fun <T> List<T>.component27(): T = this[26]
public operator fun <T> List<T>.component28(): T = this[27]
public operator fun <T> List<T>.component29(): T = this[28]
public operator fun <T> List<T>.component30(): T = this[29]
