package com.github.shwaka.kohomology.util.list

// for n in $(seq 6 15); do echo "operator fun <T> List<T>.component$n() = this[$(expr $n - 1)]"; done
// for n in $(seq 6 15); do echo "import com.github.shwaka.kohomology.util.list.component$n"; done

operator fun <T> List<T>.component6() = this[5]
operator fun <T> List<T>.component7() = this[6]
operator fun <T> List<T>.component8() = this[7]
operator fun <T> List<T>.component9() = this[8]
operator fun <T> List<T>.component10() = this[9]
operator fun <T> List<T>.component11() = this[10]
operator fun <T> List<T>.component12() = this[11]
operator fun <T> List<T>.component13() = this[12]
operator fun <T> List<T>.component14() = this[13]
operator fun <T> List<T>.component15() = this[14]
operator fun <T> List<T>.component16() = this[15]
operator fun <T> List<T>.component17() = this[16]
operator fun <T> List<T>.component18() = this[17]
operator fun <T> List<T>.component19() = this[18]
operator fun <T> List<T>.component20() = this[19]
operator fun <T> List<T>.component21() = this[20]
operator fun <T> List<T>.component22() = this[21]
operator fun <T> List<T>.component23() = this[22]
operator fun <T> List<T>.component24() = this[23]
operator fun <T> List<T>.component25() = this[24]
operator fun <T> List<T>.component26() = this[25]
operator fun <T> List<T>.component27() = this[26]
operator fun <T> List<T>.component28() = this[27]
operator fun <T> List<T>.component29() = this[28]
operator fun <T> List<T>.component30() = this[29]
