// Copied from index.html generated by github-action-benchmark

import { ChartData } from "chart.js"
import { ChartProps } from "react-chartjs-2"

import { OnChartClick } from "./useTooltip"

export type Value = { x: string, y: number }

export function getChartProps<T>(
  { datasetLabel, color, xTitle, yTitle, dataset, getValue, labels, labelToTick, onClick }: {
    datasetLabel: string
    color: `#${string}`
    xTitle: string
    yTitle: string
    dataset: T[]
    getValue: (data: T) => Value
    labels: string[]
    labelToTick: (label: string) => string
    onClick: OnChartClick
  }
): ChartProps<"line", Value[], string> {
  const data: ChartData<"line", Value[], string> = {
    labels,
    datasets: [
      {
        label: datasetLabel,
        data: dataset.map(getValue),
        borderColor: color,
        backgroundColor: color + "60", // Add alpha for #rrggbbaa
        fill: true,
        tension: 0.2,
      }
    ],
  }
  const options: ChartProps<"line", Value[], string>["options"] = {
    scales: {
      x: {
        type: "category",
        title: {
          display: true,
          text: xTitle,
        },
        ticks: {
          callback: function (tickValue: string | number): string {
            if (typeof tickValue === "string") {
              throw new Error("This can't happen!")
            }
            const label: string = this.getLabelForValue(tickValue)
            return labelToTick(label)
          }
        }
      },
      y: {
        title: {
          display: true,
          text: yTitle,
        },
        suggestedMin: 0,
      },
    },
    plugins: {
      tooltip: {
        enabled: false,
      }
    },
    onClick,
  }

  return {
    type: "line",
    data,
    options,
  }
}
