name: called-test-core

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        required: true
        type: string
        description: the version of Java
      JAVA_DISTRIBUTION:
        required: true
        type: string
        description: the distribution of Java
      CACHE_KEY_GRADLE_BUILD:
        required: true
        type: string
        description: the cache key for kohomology/.gradle, kohomology/build
    secrets:
      CODECOV_TOKEN:
        required: true
        description: token for Codecov

jobs:
  main:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: kohomology
    steps:
      - uses: actions/checkout@v3
      - name: "Cache: ~/.gradle/caches"
        uses: actions/cache@v3
        with: # use different key from build-core
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-jvm-test-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-jvm-test-
      - name: "Read cache: .gradle, build"
        uses: actions/cache@v3
        with:
          path: |
            kohomology/.gradle
            kohomology/build
          key: ${{ inputs.CACHE_KEY_GRADLE_BUILD }}
      - name: Set up JDK ${{ inputs.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ inputs.JAVA_DISTRIBUTION }}
          java-version: ${{ inputs.JAVA_VERSION }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Download dependencies # Not necessary, but useful to make the log clean
        run: ./gradlew dependencies --configuration jvmTestRuntimeClasspath --stacktrace
      - name: Compile with Gradle
        run: ./gradlew compileKotlinJvm
      - name: Test with Gradle
        run: ./gradlew jvmTest -Dkococo.debug
      - name: Jacoco Test Report
        run: ./gradlew jacocoTestReport
      - name: Upload to codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} # "token not required for public repositories" らしい…？
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t "${CODECOV_TOKEN}"
