name: build-website

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        required: true
        type: string
        description: the version of Java
      JAVA_DISTRIBUTION:
        required: true
        type: string
        description: the distribution of Java
      CACHE_KEY_GRADLE:
        required: true
        type: string
        description: the cache key for ~/.gradle/caches
      CACHE_RESTORE_KEYS_GRADLE:
        required: true
        type: string
        description: the cache restore-keys for ~/.gradle/caches
      CACHE_KEY_M2:
        required: true
        type: string
        description: the cache key for ~/.m2/repository
      CACHE_KEY_NODE_MODULES:
        required: true
        type: string
        description: the cache key for website/node_modules

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          fetch-depth: 0
      - name: "Cache: ~/.gradle/cache"
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ inputs.CACHE_KEY_GRADLE }}
          restore-keys: ${{ inputs.CACHE_RESTORE_KEYS_GRADLE }}
      - name: "Read cache: ~/.m2/repository"
        uses: actions/cache@v3
        # restore mavenLocal repository from 'build-core'
        with:
          path: ~/.m2/repository
          key: ${{ inputs.CACHE_KEY_M2 }}
      - name: "Read cache: website/node_modules"
        uses: actions/cache@v3
        with:
          path: website/node_modules
          key: ${{ inputs.CACHE_KEY_NODE_MODULES }}
      - name: Set up JDK ${{ inputs.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ inputs.JAVA_DISTRIBUTION }}
          java-version: ${{ inputs.JAVA_VERSION }}
      - name: Prepare benchmark data
        run: ./scripts/prepare-site.sh benchmark-data
      - name: Prepare dokka html
        run: ./scripts/prepare-site.sh dokka
      # - name: Use Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ env.NODE_VERSION }}
      #     cache: 'npm'
      #     cache-dependency-path: website/package-lock.json
      - uses: volta-cli/action@v3
      - name: Assert that volta is used
        run: |
          command -v node
          node --version
          command -v npm
          npm --version
        working-directory: website
      - name: Typecheck website
        run: npm run typecheck
        working-directory: website
      - name: Test components in website
        run: npm test -- --verbose
        working-directory: website
      - name: Benchmark components
        run: ./run-benchmark.sh
        working-directory: website
      - name: Store benchmark result # This should be run before building website
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: customSmallerIsBetter
          output-file-path: website/benchmark-result/output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          gh-pages-branch: benchmark-data-website
      - name: Build site
        run: npm run build
        working-directory: website
      - name: Upload
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/build
