name: called-build-website

on:
  workflow_call:
    inputs:
      CACHE_KEY_NODE_MODULES:
        required: true
        type: string
        description: the cache key for website/webapp/node_modules
      CACHE_KEY_DOKKA:
        required: true
        type: string
        description: the cache key for kohomology/build/dokka/html

jobs:
  main:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # This is necessary to read benchmark-data from separate branch.
          fetch-depth: 0
      - name: "Read cache: website/webapp/node_modules"
        uses: actions/cache@v3
        with:
          path: website/webapp/node_modules
          key: ${{ inputs.CACHE_KEY_NODE_MODULES }}
      - name: "Read cache: kohomology/build/dokka/html"
        uses: actions/cache@v3
        with:
          path: kohomology/build/dokka/html
          key: ${{ inputs.CACHE_KEY_DOKKA }}
      - name: Prepare benchmark data
        run: ./scripts/prepare-site.sh benchmark-data
      # - name: Use Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ env.NODE_VERSION }}
      #     cache: 'npm'
      #     cache-dependency-path: website/package-lock.json
      - uses: volta-cli/action@v3
      - name: Assert that volta is used
        run: ../../scripts/assert-volta.sh
        working-directory: website/webapp
        # To run "node(npm) --version", assert-volta.sh should be run in website/
      # - name: Typecheck website # moved to a separate file
      #   # This requires benchmark-data
      #   run: npm run tsc
      #   working-directory: website
      - name: Build site
        run: npm run build
        working-directory: website/webapp
      - name: Upload
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/webapp/build
