name: called-setup-website

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        required: true
        type: string
        description: the version of Java
      JAVA_DISTRIBUTION:
        required: true
        type: string
        description: the distribution of Java
      CACHE_KEY_GRADLE:
        required: true
        type: string
        description: the cache key for ~/.gradle/caches
      CACHE_KEY_M2:
        required: true
        type: string
        description: the cache key for ~/.m2/repository
    outputs:
      CACHE_KEY_NODE_MODULES:
        value: ${{ jobs.main.outputs.CACHE_KEY_NODE_MODULES }}
        description: the cache key for website/node_modules

jobs:
  main:
    runs-on: ubuntu-24.04
    outputs:
      CACHE_KEY_NODE_MODULES: ${{ steps.setup-cache-key.outputs.CACHE_KEY_NODE_MODULES }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup cache key
        id: setup-cache-key
        run: |
          {
          echo "CACHE_KEY_NODE_MODULES=${{ runner.os }}-kohomology-js-node-modules-${{ github.sha }}"
          } >> "$GITHUB_OUTPUT"
      - name: "Cache: ~/.gradle/cache"
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ inputs.CACHE_KEY_GRADLE }}
      - name: "Read cache: ~/.m2/repository"
        uses: actions/cache@v3
        # restore mavenLocal repository from 'build-core'
        with:
          path: ~/.m2/repository
          key: ${{ inputs.CACHE_KEY_M2 }}
      - name: "Save cache: website/node_modules"
        uses: actions/cache@v3
        with:
          path: website/node_modules
          key: ${{ steps.setup-cache-key.outputs.CACHE_KEY_NODE_MODULES }}
      # - name: "Save cache: website/kohomology-js/build/js"
      #   uses: actions/cache@v3 # for lint-website
      #   # actions/upload-artifact も使ってみたけど，ファイルが多すぎるせいか5分くらいかかる
      #   with:
      #     # 以下が全て必要
      #     # - build/js/packages/kohomology-js
      #     # - build/js/packages-imported/kotlin/<version>
      #     # - build/js/packages-imported/kotlin-test/<version>
      #     # - build/js/packages-imported/kotlin-test-js-runner/<version>
      #     path: website/kohomology-js/build/js
      #     key: ${{ steps.setup-cache-key.outputs.CACHE_KEY_KOHOMOLOGY_JS }}
      - name: Set up JDK ${{ inputs.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ inputs.JAVA_DISTRIBUTION }}
          java-version: ${{ inputs.JAVA_VERSION }}
      - name: Build kohomology-js
        run: ./scripts/prepare-site.sh kohomology-js
      - uses: volta-cli/action@v3
      - run: npm ci # --install-links
        # Note: --install-links is added to .npmrc
        # By --install-links, local package (kohomology-js) is copied instead of being symlinked.
        # This is necessary since actions/cache does not follow symlinks.
        working-directory: website
