name: Generate documentation

on:
  push:
    branches: [ main ]
    paths: [ 'kohomology/**', '.github/workflows/dokka.yml' ]
  pull_request:
    branches: [ main ]
    paths: [ 'kohomology/**', '.github/workflows/dokka.yml' ]
  workflow_dispatch:

jobs:
  build-jvm:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: kohomology

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-jvm-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-jvm-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Download dependencies # Not necessary, but useful to make the log clean
        run: |
          ./gradlew dependencies --configuration nativeCompileKlibraries
          ./gradlew dependencies --configuration dokkaHtmlRuntime
      - name: Generate documentation by dokka
        run: ./gradlew dokkaHtml
      - name: Upload
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "kohomology/build/dokka/html"
