name: Test # This will be shown in the badge in README.md
# name: Test, benchmark, and generate site

on:
  push:
    branches: [ main ]
    paths: [ 'kohomology/**', 'profile/**', 'website/**', 'prepare-site.sh', '.github/workflows/gradle.yml' ]
  # pull_request: # See pull_request.yml for workflows on pull requests
  #   branches: [ main ]
  #   paths: [ 'kohomology/**', 'profile/**', '.github/workflows/gradle.yml' ]
  workflow_dispatch:

jobs:
  test-and-lint:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: kohomology
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-jvm-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-jvm-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Download dependencies # Not necessary, but useful to make the log clean
        run: ./gradlew dependencies --configuration jvmTestRuntimeClasspath --stacktrace
      - name: Compile with Gradle
        run: ./gradlew compileKotlinJvm
      - name: Test with Gradle
        run: ./gradlew jvmTest -Dkococo.debug
      - name: Jacoco Test Report
        run: ./gradlew jacocoTestReport
      - name: Upload to codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} # "token not required for public repositories" らしい…？
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}
      - name: Check with ktlint
        run: ./gradlew ktlintCheck

  benchmark:
    needs: test-and-lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-jvm-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-jvm-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install kohomology to MavenLocal
        run: ./gradlew publishToMavenLocal
        working-directory: kohomology
      - name: Run benchmark
        run: ./gradlew benchmark
        working-directory: profile
      - name: Format benchmark result
        run: ./gradlew formatBenchmarkResult
        working-directory: profile
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: customSmallerIsBetter
          output-file-path: profile/build/kohomology/benchmark/output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          gh-pages-branch: benchmark-data

  generate-site:
    # needs: [ test-and-lint, benchmark ]
    runs-on: ubuntu-latest
    env:
      BENCHMARK_DATA_DIR: benchmark-data
    steps:
      - uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          fetch-depth: 0
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-jvm-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-jvm-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Prepare benchmark data and dokka html
        run: ./prepare-site.sh
      # - name: Download dependencies # Not necessary, but useful to make the log clean
      #   run: |
      #     ./gradlew dependencies --configuration nativeCompileKlibraries --stacktrace
      #     ./gradlew dependencies --configuration dokkaHtmlRuntime --stacktrace
      #   working-directory: kohomology
      # - name: Generate documentation by dokka
      #   run: ./gradlew dokkaHtml
      #   working-directory: kohomology
      # - name: Compute coverage
      #   run: ./gradlew dokkacovWriteJson
      #   working-directory: kohomology
      # - name: Checkout benchmark-data branch as a subdirectory
      #   uses: actions/checkout@v2
      #   with:
      #     path: ${{ env.BENCHMARK_DATA_DIR }}
      #     ref: benchmark-data
      # - name: Build site
      #   run: |
      #     mkdir site
      #     cp -r kohomology/build/dokka/html site/dokka
      #     cp -r $BENCHMARK_DATA_DIR/dev/bench site/benchmark
      #     cp index.html site/index.html
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'
          cache-dependency-path: website/package-lock.json
      - run: npm install
        working-directory: website
      - name: Build site
        run: npm run build
        working-directory: website
      - name: Upload
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/build
