name: Build # This will be shown in the badge in README.md
# name: Test, benchmark, and generate site

env:
  JAVA_DISTRIBUTION: zulu # default value in actions/setup-java@v1
  JAVA_VERSION: 8
  # NODE_VERSION: 16.x # node version is specified in package.json by using volta
  # 'env' cannot be used in 'runs-on'(?)
  SHARED_ARTIFACT_NAME: _internal_artifact
  SHARED_ARTIFACT_PATH: website/kohomology-js/build/js

on:
  push:
    branches: [ main ]
    paths: [ 'kohomology/**', 'profile/**', 'website/**', 'scripts/prepare-site.sh', '.github/workflows/main.yml' ]
  # pull_request: # See pull_request.yml for workflows on pull requests
  #   branches: [ main ]
  #   paths: [ 'kohomology/**', 'profile/**', '.github/workflows/gradle.yml' ]
  workflow_dispatch:

jobs:
  prepare-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: setup
        run: |
          echo "hash-gradle-kts=${{ hashFiles('**/*.gradle.kts') }}" >> "$GITHUB_OUTPUT"
    outputs:
      JAVA_DISTRIBUTION: ${{ env.JAVA_DISTRIBUTION }}
      JAVA_VERSION: ${{ env.JAVA_VERSION }}

  build-core:
    needs: [ prepare-env ]
    uses: ./.github/workflows/build-core.yml
    with:
      JAVA_DISTRIBUTION: ${{ needs.prepare-env.outputs.JAVA_DISTRIBUTION }}
      JAVA_VERSION: ${{ needs.prepare-env.outputs.JAVA_VERSION }}

  test-core:
    needs: [ build-core ]
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: kohomology
    steps:
      - uses: actions/checkout@v3
      - name: "Cache: ~/.gradle/caches"
        uses: actions/cache@v3
        with: # use different key from build-core
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-jvm-test-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-jvm-test-
      - name: "Read cache: .gradle, build"
        uses: actions/cache@v3
        with:
          path: |
            kohomology/.gradle
            kohomology/build
          key: ${{ runner.os }}-gradle-build-${{ github.sha }}
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Download dependencies # Not necessary, but useful to make the log clean
        run: ./gradlew dependencies --configuration jvmTestRuntimeClasspath --stacktrace
      - name: Compile with Gradle
        run: ./gradlew compileKotlinJvm
      - name: Test with Gradle
        run: ./gradlew jvmTest -Dkococo.debug
      - name: Jacoco Test Report
        run: ./gradlew jacocoTestReport
      - name: Upload to codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} # "token not required for public repositories" らしい…？
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}

  benchmark-core:
    needs: [ prepare-env, build-core ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: "Cache: ~/.gradle/caches"
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ needs.build-core.outputs.CACHE_KEY_GRADLE }}
          restore-keys: ${{ needs.build-core.outputs.CACHE_RESTORE_KEYS_GRADLE }}
      - name: "Read cache: ~/.m2/repository"
        uses: actions/cache@v3
        # restore mavenLocal repository from 'build-core'
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-kohomology-maven-local-${{ github.sha }}
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Run benchmark
        run: ./gradlew benchmark -DbenchmarkTarget=com.github.shwaka.kohomology.profile.KohomologyBenchmark
        working-directory: profile
      - name: Format benchmark result
        run: ./gradlew formatBenchmarkResult
        working-directory: profile
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: customSmallerIsBetter
          output-file-path: profile/build/kohomology/benchmark/output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          gh-pages-branch: benchmark-data

  build-website:
    needs: [ prepare-env, build-core, test-core, benchmark-core ]
    runs-on: ubuntu-20.04
    env:
      BENCHMARK_DATA_DIR: benchmark-data
    steps:
      - uses: actions/checkout@v3
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          fetch-depth: 0
      - name: "Cache: ~/.gradle/cache"
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ needs.build-core.outputs.CACHE_KEY_GRADLE }}
          restore-keys: ${{ needs.build-core.outputs.CACHE_RESTORE_KEYS_GRADLE }}
      - name: "Read cache: ~/.m2/repository"
        uses: actions/cache@v3
        # restore mavenLocal repository from 'build-core'
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-kohomology-maven-local-${{ github.sha }}
      - name: "Save cache: website/kohomology-js/build/js"
        uses: actions/cache@v3 # for lint-website
        # actions/upload-artifact も使ってみたけど，ファイルが多すぎるせいか5分くらいかかる
        with:
          # 以下が全て必要
          # - build/js/packages/kohomology-js
          # - build/js/packages-imported/kotlin/<version>
          # - build/js/packages-imported/kotlin-test/<version>
          # - build/js/packages-imported/kotlin-test-js-runner/<version>
          path: website/kohomology-js/build/js
          key: ${{ runner.os }}-kohomology-js-node-package-${{ github.sha }}
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Prepare benchmark data and dokka html
        run: ./scripts/prepare-site.sh
      - name: Assert samples are working
        run: ./scripts/run-sample.sh
      # - name: Use Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ env.NODE_VERSION }}
      #     cache: 'npm'
      #     cache-dependency-path: website/package-lock.json
      - uses: volta-cli/action@v3
      - name: Assert that volta is used
        run: |
          which node
          node --version
          which npm
          npm --version
        working-directory: website
      - run: npm ci
        working-directory: website
      - name: Typecheck website
        run: npm run typecheck
        working-directory: website
      - name: Test components in website
        run: npm test -- --verbose
        working-directory: website
      - name: Benchmark components
        run: ./run-benchmark.sh
        working-directory: website
      - name: Store benchmark result # This should be run before building website
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: customSmallerIsBetter
          output-file-path: website/benchmark-result/output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          gh-pages-branch: benchmark-data-website
      - name: Build site
        run: npm run build
        working-directory: website
      - name: Upload
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/build

  lint-core:
    needs: [ build-core ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: detekt
        run: ./gradlew detekt
        working-directory: kohomology

  lint-website:
    needs: [ build-website ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      # - name: Use Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ env.NODE_VERSION }}
      #     cache: 'npm'
      #     cache-dependency-path: website/package-lock.json
      - uses: volta-cli/action@v3
      - name: "Read cache: website/kohomology-js/build/js"
        uses: actions/cache@v3 # restore from build-website
        # actions/download-artifact も使ってみたけど，ファイルが多すぎるせいか5分くらいかかる
        with:
          # 以下が全て必要
          # - build/js/packages/kohomology-js
          # - build/js/packages-imported/kotlin/<version>
          # - build/js/packages-imported/kotlin-test/<version>
          # - build/js/packages-imported/kotlin-test-js-runner/<version>
          path: website/kohomology-js/build/js
          key: ${{ runner.os }}-kohomology-js-node-package-${{ github.sha }}
      - run: npm ci
        working-directory: website
      - name: eslint
        run: npm run eslint
        working-directory: website
