name: Build # This will be shown in the badge in README.md
# name: Test, benchmark, and generate site

env:
  JAVA_DISTRIBUTION: zulu # default value in actions/setup-java@v1
  JAVA_VERSION: 8
  # NODE_VERSION: 16.x # node version is specified in package.json by using volta
  # 'env' cannot be used in 'runs-on'(?)

on:
  push:
    branches: [ main ]
    paths: [ 'kohomology/**', 'profile/**', 'website/**', 'scripts/prepare-site.sh', '.github/workflows/main.yml', '.github/workflows/called-*.yml' ]
  # pull_request: # See pull_request.yml for workflows on pull requests
  #   branches: [ main ]
  #   paths: [ 'kohomology/**', 'profile/**', '.github/workflows/gradle.yml' ]
  workflow_dispatch:

jobs:
  prepare-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    outputs:
      JAVA_DISTRIBUTION: ${{ env.JAVA_DISTRIBUTION }}
      JAVA_VERSION: ${{ env.JAVA_VERSION }}

  build-core:
    needs: [ prepare-env ]
    uses: ./.github/workflows/called-build-core.yml
    with:
      JAVA_DISTRIBUTION: ${{ needs.prepare-env.outputs.JAVA_DISTRIBUTION }}
      JAVA_VERSION: ${{ needs.prepare-env.outputs.JAVA_VERSION }}

  test-core:
    needs: [ prepare-env, build-core ]
    uses: ./.github/workflows/called-test-core.yml
    with:
      JAVA_DISTRIBUTION: ${{ needs.prepare-env.outputs.JAVA_DISTRIBUTION }}
      JAVA_VERSION: ${{ needs.prepare-env.outputs.JAVA_VERSION }}
      CACHE_KEY_GRADLE_BUILD: ${{ needs.build-core.outputs.CACHE_KEY_GRADLE_BUILD }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  benchmark-core:
    needs: [ prepare-env, build-core ]
    uses: ./.github/workflows/called-benchmark-core.yml
    with:
      JAVA_DISTRIBUTION: ${{ needs.prepare-env.outputs.JAVA_DISTRIBUTION }}
      JAVA_VERSION: ${{ needs.prepare-env.outputs.JAVA_VERSION }}
      CACHE_KEY_GRADLE: ${{ needs.build-core.outputs.CACHE_KEY_GRADLE }}
      CACHE_RESTORE_KEYS_GRADLE: ${{ needs.build-core.outputs.CACHE_RESTORE_KEYS_GRADLE }}
      CACHE_KEY_M2: ${{ needs.build-core.outputs.CACHE_KEY_M2 }}

  docs-core:
    needs: [ prepare-env, build-core ]
    uses: ./.github/workflows/called-docs-core.yml
    with:
      JAVA_DISTRIBUTION: ${{ needs.prepare-env.outputs.JAVA_DISTRIBUTION }}
      JAVA_VERSION: ${{ needs.prepare-env.outputs.JAVA_VERSION }}
      CACHE_KEY_GRADLE: ${{ needs.build-core.outputs.CACHE_KEY_GRADLE }}
      CACHE_RESTORE_KEYS_GRADLE: ${{ needs.build-core.outputs.CACHE_RESTORE_KEYS_GRADLE }}

  build-kotlin-js:
    needs: [ prepare-env, build-core ]
    uses: ./.github/workflows/called-build-kotlin-js.yml
    with:
      JAVA_DISTRIBUTION: ${{ needs.prepare-env.outputs.JAVA_DISTRIBUTION }}
      JAVA_VERSION: ${{ needs.prepare-env.outputs.JAVA_VERSION }}
      CACHE_KEY_GRADLE: ${{ needs.build-core.outputs.CACHE_KEY_GRADLE }}
      CACHE_RESTORE_KEYS_GRADLE: ${{ needs.build-core.outputs.CACHE_RESTORE_KEYS_GRADLE }}
      CACHE_KEY_M2: ${{ needs.build-core.outputs.CACHE_KEY_M2 }}

  test-website:
    needs: [ build-kotlin-js ]
    uses: ./.github/workflows/called-test-website.yml
    with:
      CACHE_KEY_NODE_MODULES: ${{ needs.build-kotlin-js.outputs.CACHE_KEY_NODE_MODULES }}

  build-website:
    needs: [ test-core, benchmark-core, docs-core, build-kotlin-js, test-website ]
    uses: ./.github/workflows/called-build-website.yml
    with:
      CACHE_KEY_NODE_MODULES: ${{ needs.build-kotlin-js.outputs.CACHE_KEY_NODE_MODULES }}
      CACHE_KEY_DOKKA: ${{ needs.docs-core.outputs.CACHE_KEY_DOKKA }}

  lint-core:
    needs: [ prepare-env, build-core ]
    uses: ./.github/workflows/called-lint-core.yml
    with:
      JAVA_DISTRIBUTION: ${{ needs.prepare-env.outputs.JAVA_DISTRIBUTION }}
      JAVA_VERSION: ${{ needs.prepare-env.outputs.JAVA_VERSION }}

  lint-website:
    needs: [ build-kotlin-js ]
    uses: ./.github/workflows/called-lint-website.yml
    with:
      CACHE_KEY_NODE_MODULES: ${{ needs.build-kotlin-js.outputs.CACHE_KEY_NODE_MODULES }}
