name: Build # This will be shown in the badge in README.md
# name: Test, benchmark, and generate site

env:
  JAVA_DISTRIBUTION: zulu # default value in actions/setup-java@v1
  JAVA_VERSION: 8
  # NODE_VERSION: 16.x # node version is specified in package.json by using volta
  # 'env' cannot be used in 'runs-on'(?)
  SHARED_ARTIFACT_NAME: _internal_artifact
  SHARED_ARTIFACT_PATH: website/kohomology-js/build/js

on:
  push:
    branches: [ main ]
    paths: [ 'kohomology/**', 'profile/**', 'website/**', 'scripts/prepare-site.sh', '.github/workflows/main.yml' ]
  # pull_request: # See pull_request.yml for workflows on pull requests
  #   branches: [ main ]
  #   paths: [ 'kohomology/**', 'profile/**', '.github/workflows/gradle.yml' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: kohomology
    steps:
      - uses: actions/checkout@v3
      - name: "Cache: ~/.gradle/caches"
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-jvm-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-jvm-
      - name: "Save cache: ~/.m2/repository"
        uses: actions/cache@v3
        # will be restored in 'benchmark' and 'generate-site'
        with:
          path: ~/.m2/repository
          # Add ${{ github.sha }} to ensure that the result will be always saved to the cache
          # https://qiita.com/yuki0n0/items/d52e1fbbed08bc263101
          key: ${{ runner.os }}-kohomology-maven-local-${{ github.sha }}
      - name: "Save cache: .gradle, build"
        uses: actions/cache@v3
        # will be restored in test
        with:
          path: |
            kohomology/.gradle
            kohomology/build
          key: ${{ runner.os }}-gradle-build-${{ github.sha }}
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Download dependencies # Not necessary, but useful to make the log clean
        run: ./gradlew dependencies --configuration jvmTestRuntimeClasspath --stacktrace
      - name: Compile with Gradle
        run: ./gradlew compileKotlinJvm
      - name: Install kohomology to MavenLocal
        # This publication will be saved by actions/cache.
        # Native publication is not used in later workflows.
        # Note that publish{Jvm,Js}PublicationToMavenLocal shouldn't be used here.
        # If they were used, then -jvm and -js would be required when writing dependency.
        run: ./gradlew publishToMavenLocal -Dkohomology.disableNative

  test:
    needs: build
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: kohomology
    steps:
      - uses: actions/checkout@v3
      - name: "Cache: ~/.gradle/caches"
        uses: actions/cache@v3
        with: # use different key from build
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-jvm-test-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-jvm-test-
      - name: "Read cache: .gradle, build"
        uses: actions/cache@v3
        with:
          path: |
            kohomology/.gradle
            kohomology/build
          key: ${{ runner.os }}-gradle-build-${{ github.sha }}
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Download dependencies # Not necessary, but useful to make the log clean
        run: ./gradlew dependencies --configuration jvmTestRuntimeClasspath --stacktrace
      - name: Compile with Gradle
        run: ./gradlew compileKotlinJvm
      - name: Test with Gradle
        run: ./gradlew jvmTest -Dkococo.debug
      - name: Jacoco Test Report
        run: ./gradlew jacocoTestReport
      - name: Upload to codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} # "token not required for public repositories" らしい…？
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}

  benchmark:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: "Cache: ~/.gradle/caches"
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-jvm-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-jvm-
      - name: "Read cache: ~/.m2/repository"
        uses: actions/cache@v3
        # restore mavenLocal repository from 'build'
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-kohomology-maven-local-${{ github.sha }}
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Run benchmark
        run: ./gradlew benchmark -DbenchmarkTarget=com.github.shwaka.kohomology.profile.KohomologyBenchmark
        working-directory: profile
      - name: Format benchmark result
        run: ./gradlew formatBenchmarkResult
        working-directory: profile
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: customSmallerIsBetter
          output-file-path: profile/build/kohomology/benchmark/output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          gh-pages-branch: benchmark-data

  generate-site:
    needs: [ build, test, benchmark ]
    runs-on: ubuntu-20.04
    env:
      BENCHMARK_DATA_DIR: benchmark-data
    steps:
      - uses: actions/checkout@v3
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          fetch-depth: 0
      - name: "Cache: ~/.gradle/cache"
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-jvm-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-jvm-
      - name: "Read cache: ~/.m2/repository"
        uses: actions/cache@v3
        # restore mavenLocal repository from 'build'
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-kohomology-maven-local-${{ github.sha }}
      - name: "Save cache: website/kohomology-js/build/js"
        uses: actions/cache@v3 # for lint-website
        # actions/upload-artifact も使ってみたけど，ファイルが多すぎるせいか5分くらいかかる
        with:
          # 以下が全て必要
          # - build/js/packages/kohomology-js
          # - build/js/packages-imported/kotlin/<version>
          # - build/js/packages-imported/kotlin-test/<version>
          # - build/js/packages-imported/kotlin-test-js-runner/<version>
          path: website/kohomology-js/build/js
          key: ${{ runner.os }}-kohomology-js-node-package-${{ github.sha }}
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Prepare benchmark data and dokka html
        run: ./scripts/prepare-site.sh
      - name: Assert samples are working
        run: ./scripts/run-sample.sh
      # - name: Use Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ env.NODE_VERSION }}
      #     cache: 'npm'
      #     cache-dependency-path: website/package-lock.json
      - uses: volta-cli/action@v3
      - name: Assert that volta is used
        run: |
          which node
          node --version
          which npm
          npm --version
        working-directory: website
      - run: npm ci
        working-directory: website
      - name: Typecheck website
        run: npm run typecheck
        working-directory: website
      - name: Test components in website
        run: npm test
        working-directory: website
      - name: Build site
        run: npm run build
        working-directory: website
      - name: Benchmark components
        run: ./run-benchmark.sh
        working-directory: website
      - name: Upload
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/build

  lint-kotlin:
    needs: [ build ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: detekt
        run: ./gradlew detekt
        working-directory: kohomology

  lint-website:
    needs: [ generate-site ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      # - name: Use Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ env.NODE_VERSION }}
      #     cache: 'npm'
      #     cache-dependency-path: website/package-lock.json
      - uses: volta-cli/action@v3
      - name: "Read cache: website/kohomology-js/build/js"
        uses: actions/cache@v3 # restore from generate-site
        # actions/download-artifact も使ってみたけど，ファイルが多すぎるせいか5分くらいかかる
        with:
          # 以下が全て必要
          # - build/js/packages/kohomology-js
          # - build/js/packages-imported/kotlin/<version>
          # - build/js/packages-imported/kotlin-test/<version>
          # - build/js/packages-imported/kotlin-test-js-runner/<version>
          path: website/kohomology-js/build/js
          key: ${{ runner.os }}-kohomology-js-node-package-${{ github.sha }}
      - run: npm ci
        working-directory: website
      - name: eslint
        run: npm run eslint
        working-directory: website
