name: Run sample

on:
  push:
    branches: [ main ]
    paths: [ 'sample/**', '.github/workflows/run_sample.yml' ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        distribution: [zulu, microsoft, temurin]
        version: [8, 11, 17]
        exclude:
          - distribution: microsoft
            version: 8
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-jvm-${{ matrix.distribution }}-${{ matrix.version }}-${{ hashFiles('**/*.gradle.kts') }}
      - name: Setup JDK (${{ matrix.distribution }}, ${{ matrix.version }})
        uses: actions/setup-java@v2
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.version }}
      - run: ./scripts/run-sample.sh
