name: Run template

on:
  push:
    branches: [ main ]
    paths: [ 'template/**', '.github/workflows/run_template.yml' ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-jvm-template-${{ hashFiles('**/*.gradle.kts') }}
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8
      - run: ./runner.sh
        working-directory: template
        if: matrix.os != 'windows-latest'
      - run: ./runner.bat
        working-directory: template
        if: matrix.os == 'windows-latest'
