name: Run sample

# sample/ should use released version of kohomology

on:
  push:
    branches: [ main ]
    paths: [ 'kohomology/**', 'sample/**', '.github/workflows/run_sample.yml', 'scripts/run-sample.py', 'scripts/sample.json' ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        distribution: [zulu, microsoft, temurin]
        version: [8, 11, 17]
        exclude:
          - distribution: microsoft
            version: 8
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-jvm-${{ matrix.distribution }}-${{ matrix.version }}-${{ hashFiles('**/*.gradle.kts') }}
        if: matrix.os != 'windows-latest'
        # caching does not work on Windows (maybe this is because the path contains "~" and "/")
      - name: Setup JDK (${{ matrix.distribution }}, ${{ matrix.version }})
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.version }}
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: python scripts/run-sample.py
